### PR TITLE
Fix/v2.7.0 compatibility

### PR DESCRIPTION
**Pull request by AustinTSchaffer**

### CODE REVIEW

**Comment by lorawoodford** [comment]
Hi @AustinTSchaffer ,

Thanks so much for working on this!  This looks great, but I have a few questions about what happens when the tool encounters no existing data to migrate.  

First, I see on ln 1530 that the default finding_aid_script is being set to `Latn`.  By default, the 2.7 upgrade sets this new required value to `Zyyy` (Code for undetermined script).  Can this line be updated to follow the same behavior?  The Program Team has written a few plugins that will allow for these to be changed en masse via background jobs, but as a starting point it was decided that `Zyyy` was most appropriate.

Second, what occurs during the migration if no language of material (for resources only) or finding aid language is provided?  (I can't even recall -- were these both optional in the AT?).  On the ArchivesSpace side these two language codes are newly required fields for resource records as of 2.7 (a language of materials language remains optional for digital objects, digital object components, and archival objects).  With this change in the data model, I want to ensure that migrations will still go through in cases where these language codes are missing.

Let me know if you have questions, and thanks so much again!

**Comment by AustinTSchaffer** [comment]
@lorawoodford ,

Thank you for the response and the info. I have updated the script code accordingly. I'll be sure to make note of that behavior for Atlas's tools as well.

I am not sure if AT requires any language fields, but there is handling in the current AT migrator that indicates that languageCode might not have a value in some cases.

For the non-`resource` implementations of abstract-archival-object, the AT migrator will check to make sure that the language code is not null nor empty before adding the "lang_materials" property to the JSON record. This is similar to how the `addLanguageCode` method works, which only populates the "language" property if the language code is not null nor empty.

On `resource` records specifically, the AT migrator will add a "lang_materials" property regardless of whether the language code has a value. Both the `addLangMaterials` and `addLanguageCode` methods use `enumUtil.getASpaceLanguageCode(languageCode)` in order to convert the AT language code to an ASpace language code. `enumUtil.getASpaceLanguageCode` returns `"und"` in a lot of cases, including the case where language code is null or empty.

Looking at that method again, I have decided to change it just to make sure it returns `"und"` in all failing cases. It looks like there was a case where the method could return `"other_unmapped"`, but that never came up during any of the migrations that I've ever done.

**Comment by AustinTSchaffer** [comment]
As for cases where "finding aid language" is provided on AT resources, I made sure the AT migrator uses the Resource's language code `enumUtil.getASpaceLanguageCode(record.getLanguageCode())` for `"finding_aid_language"`, since there seems to be a lot of variability in AT's `languageOfFindingAid` field. I instead rerouted the data from `record.getLanguageOfFindingAid()` to the resource model's new `"finding_aid_language_note"` field.

**Comment by AustinTSchaffer** [comment]
Just a final note on this pull request, I've left the `"language"` field in so the AT language code will still be migrated to ArchivesSpace if the tool is used against a version of ArchivesSpace that is earlier than v2.7.0. However, doing so will lose the data from the languageOfFindingAid field.

**Comment by lorawoodford** [comment]
Perfect @AustinTSchaffer - thanks for these clarifications!  Exactly the information I was looking for.

Regarding your last comment - thanks for thinking about the implications of running this tool for migrations into pre-2.7 releases, but since the migration tool is going to be versioned and tied to a specific ArchivesSpace release (I believe this new migration tool will be v3.0, but @lmcglohon can answer for sure), there's no need to make this backwards compatible.  Especially since it won't fully handle the new language of description requirements of 2.7+.  So it would be our preference to have the legacy `"language"` removed at this time to avoid a need to do future code maintenance/cleanup.

When that's done, I'll merge and @lmcglohon will build the new migration tool release.

Thanks again!

**Comment by AustinTSchaffer** [comment]
@lorawoodford ,

Sure thing, that all makes sense to me. I've removed the method that adds the "language" property to those 4 models.

Have a great weekend,
Austin

**Comment by lorawoodford** [comment]
Thanks @AustinTSchaffer !

**Pull request merged**
